# Generated by Django 5.0 on 2023-12-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
